version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
      - echo $env(prefix)
      - serverless deploy
      # - serverless deploy --stage cicd | tee deploy.out
  post_build:
    commands:
      - echo Build completed on `date`