version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage cicd | tee deploy.out
# 11  post_build:
#     commands:
#       - . ./test.sh



# version: 0.1

# phases:
#     install:
#          commands:
#             - npm install
#             - npm install -g mocha
#             - npm install -g serverless
#     build:
#          commands:
#             - mkdir artifacts
#             - dotnet publish -c Release -o out
#             - cd out && zip -r ../publish.zip ./*
#     post_build:
#          commands:
#             - serverless deploy --stage $env --region us-west-2 --verbose

# artifacts:
#     files:
#          - serverless.yml
#          - publish.zip
#          - promotion.sh
#     discard-paths: yes