version: 0.1
phases:
  install:
    commands:
      - cd app
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
     
      - serverless deploy --stage cicd | tee deploy.out
